### ISSUE TITLE
Server Error on Flathub version on Fedora 36

### ISSUE THREAD

**Issue by jsagfr** [flathub/org.jamovi.jamovi#80]
Hello,

I'm trying to install Jamovi from Flathub on a Fedora 36 Workstation and Fedora 36. When Jamovi is started, a generic error window appears with:

> **Server Error**
> Unfortunately, the jamovi server could not be started, and jamovi must now close. We regret the inconvenience.
> Please report your experiences to the jamovi team.

Launching the app in verbose command line gives:

```
[user@machine ~]$ flatpak run --verbose org.jamovi.jamovi
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening user flatpak installation at path /var/home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/c7252386179c4c1ecf5d93bdaec6ca82852dddfdae7112b5c3177f7424c4a928/files/lib32 does not exist
F: Cleaning up unused container id 1362224910
F: Cleaning up per-app-ID state for org.jamovi.jamovi
F: Cleaning up unused container id 554911718
F: Cleaning up per-app-ID state for org.jamovi.jamovi
F: Allocated instance id 3084481312
F: Add defaults in dir /org/jamovi/jamovi/
F: Add locks in dir /org/jamovi/jamovi/
F: Allowing dri access
F: Allowing homedir access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/var/home/user/.config/pulse/client.conf': Error opening file /var/home/user/.config/pulse/client.conf: Aucun fichier ou dossier de ce type
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 jamovi'
Gtk-Message: 10:42:16.047: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:42:16.048: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.9/site-packages/jamovi/server/__main__.py", line 7, in <module>
    from .server import Server
  File "/app/lib/python3.9/site-packages/jamovi/server/server.py", line 12, in <module>
    from .clientconnection import ClientConnection
  File "/app/lib/python3.9/site-packages/jamovi/server/clientconnection.py", line 5, in <module>
    from .session import NoSuchInstanceException
  File "/app/lib/python3.9/site-packages/jamovi/server/session.py", line 15, in <module>
    from .instance import Instance
  File "/app/lib/python3.9/site-packages/jamovi/server/instance.py", line 20, in <module>
    from .modules import Modules
  File "/app/lib/python3.9/site-packages/jamovi/server/modules/__init__.py", line 2, in <module>
    from .modules import Modules
  File "/app/lib/python3.9/site-packages/jamovi/server/modules/modules.py", line 23, in <module>
    from yaml import CSafeLoader as Loader
ImportError: cannot import name 'CSafeLoader' from 'yaml' (/app/lib/python3.9/site-packages/yaml/__init__.py)

Failed to start (1)
(node:5) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from undefined
    at NavigationController.loadURL (electron/js2c/browser_init.js:205:2492)
    at BrowserWindow.n.loadURL (electron/js2c/browser_init.js:33:1923)
    at createWindow (/app/bin/resources/default_app.asar/main.js:593:10)
    at handleCommand (/app/bin/resources/default_app.asar/main.js:500:9)
    at /app/bin/resources/default_app.asar/main.js:438:5
(node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Details on OS configuration:
```
[user@machine ~]$ cat /etc/fedora-release 
Fedora release 36 (Thirty Six)
[user@machine ~]$ flatpak --version
Flatpak 1.12.7
```

**Comment by jonathon-love** [comment]
see [here](https://github.com/jamovi/jamovi/issues/1250).

**Comment by jsagfr** [comment]
OK, it's a duplicated issue: same problem, same workaround!

Thank you for your reactivity :smile: 

I close this issue.
